tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "on-secondary": "#ffffff",
                "on-secondary-container": "#4c4a84",
                "on-primary-fixed-variant": "#372abf",
                "on-tertiary-fixed-variant": "#7d2d00",
                "secondary-fixed": "#e3dfff",
                "primary": "#2a14b4",
                "inverse-surface": "#2e3132",
                "secondary-fixed-dim": "#c3c0ff",
                "inverse-on-surface": "#f0f1f2",
                "on-secondary-fixed": "#16124c",
                "on-error-container": "#93000a",
                "outline-variant": "#c7c4d7",
                "on-surface": "#191c1d",
                "on-tertiary-fixed": "#360f00",
                "surface-container-low": "#f3f4f5",
                "on-primary": "#ffffff",
                "on-primary-fixed": "#100069",
                "error-container": "#ffdad6",
                "secondary-container": "#c0bdff",
                "surface-variant": "#e1e3e4",
                "surface-dim": "#d9dadb",
                "on-tertiary-container": "#ffb393",
                "inverse-primary": "#c3c0ff",
                "surface-tint": "#5148d7",
                "surface-container-lowest": "#ffffff",
                "outline": "#777586",
                "on-tertiary": "#ffffff",
                "error": "#ba1a1a",
                "on-surface-variant": "#464554",
                "surface-container-highest": "#e1e3e4",
                "surface-container": "#edeeef",
                "surface": "#f8f9fa",
                "tertiary-container": "#8f3400",
                "on-background": "#191c1d",
                "primary-fixed-dim": "#c3c0ff",
                "tertiary": "#692400",
                "tertiary-fixed-dim": "#ffb597",
                "tertiary-fixed": "#ffdbcd",
                "on-error": "#ffffff",
                "surface-container-high": "#e7e8e9",
                "primary-container": "#4338ca",
                "on-secondary-fixed-variant": "#42407a",
                "on-primary-container": "#c1beff",
                "surface-bright": "#f8f9fa",
                "secondary": "#5a5893",
                "primary-fixed": "#e3dfff",
                "background": "#f8f9fa"
            },
            "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            "fontFamily": {
                "sans": ["Inter", "sans-serif"],
                "headline": ["Inter", "sans-serif"],
                "body": ["Inter", "sans-serif"],
                "label": ["Inter", "sans-serif"]
            }
        },
    },
}
